### PR TITLE
Update Renovate Settings

### PR DESCRIPTION
**Pull request by charlie-tf**
- Set `:preserveSemverRanges` preset to preserve `^`s
- Runs each weekend so PRs are ready by Monday morning
- Give 3 days for package versions to stabilize
- Label Major PRs as `UPDATE-MAJOR`

### CODE REVIEW

**Review by karthikbtf — APPROVED** [review]
Thank you 🙏 
Does 'every weekend' imply that PRs will be out on Monday?

**Comment by charlie-tf** [comment]
> Thank you 🙏 Does 'every weekend' imply that PRs will be out on Monday?

Yeah, they should actually go out on the weekend (maybe Saturday?) and be ready for whoever plans to take care of them for the week on Monday.

**Comment by karthikbtf** [comment]
> > Thank you 🙏 Does 'every weekend' imply that PRs will be out on Monday?
> 
> Yeah, they should actually go out on the weekend (maybe Saturday?) and be ready for whoever plans to take care of them for the week on Monday.

sg.. similar to terraware-server i presume
thanks for doing this

**Review by constanzauanini — APPROVED** [review]
Cool! Thank you!!

**Pull request merged**
