### PR TITLE
Auto-Increment Version Update

### PR DESCRIPTION
**Pull request by charlie-tf**
- Use token, email, and username from terraformation-deploy user
- Secrets are in place; this should fix the version-bump job

### CODE REVIEW

**Review by karthikbtf — APPROVED** [review]
🎉 
@charlie-tf maybe remove the `patch` label here?

**Comment by charlie-tf** [comment]
> 🎉 @charlie-tf maybe remove the `patch` label here?

I was kinda thinking to keep it in place as a test. But certainly there will be another PR that'll test this out for us soon, so I'll remove it.

**Comment by charlie-tf** [comment]
Oh, oops, I didn't notice that github-actions re-added the `patch` label before merging 🤦 . I guess this will be a test after all. cc @karthikbtf

**Comment by karthikbtf** [comment]
> Oh, oops, I didn't notice that github-actions re-added the `patch` label before merging 🤦 . I guess this will be a test after all. cc @karthikbtf

@charlie-tf all good! Lol
Quick question, will 'patch' be applied to all PRs automatically? Will we be able to merge PRs that don't need a version bump?

**Comment by charlie-tf** [comment]
> > Oh, oops, I didn't notice that github-actions re-added the `patch` label before merging 🤦 . I guess this will be a test after all. cc @karthikbtf
> 
> @charlie-tf all good! Lol Quick question, will 'patch' be applied to all PRs automatically? Will we be able to merge PRs that don't need a version bump?

If you don't want a version bump, then you'd need to make sure there's no patch, minor, or major label on the PR prior to merging it. I pushed a commit (merge main) after removing the label, which kicked off another "Add Labels" job and re-added it. It's totally possible to merge without a version bump though.

**Comment by karthikbtf** [comment]
> > > Oh, oops, I didn't notice that github-actions re-added the `patch` label before merging 🤦 . I guess this will be a test after all. cc @karthikbtf
> > 
> > 
> > @charlie-tf all good! Lol Quick question, will 'patch' be applied to all PRs automatically? Will we be able to merge PRs that don't need a version bump?
> 
> If you don't want a version bump, then you'd need to make sure there's no patch, minor, or major label on the PR prior to merging it. I pushed a commit (merge main) after removing the label, which kicked off another "Add Labels" job and re-added it. It's totally possible to merge without a version bump though.

Awesome, thanks!!

**Comment by charlie-tf** [comment]
> > > > Oh, oops, I didn't notice that github-actions re-added the `patch` label before merging 🤦 . I guess this will be a test after all. cc @karthikbtf
> > > 
> > > 
> > > @charlie-tf all good! Lol Quick question, will 'patch' be applied to all PRs automatically? Will we be able to merge PRs that don't need a version bump?
> > 
> > 
> > If you don't want a version bump, then you'd need to make sure there's no patch, minor, or major label on the PR prior to merging it. I pushed a commit (merge main) after removing the label, which kicked off another "Add Labels" job and re-added it. It's totally possible to merge without a version bump though.
> 
> Awesome, thanks!!

@karthikbtf Looks like it actually worked though! 🎉 
image

**Comment by karthikbtf** [comment]
> > > > > Oh, oops, I didn't notice that github-actions re-added the `patch` label before merging 🤦 . I guess this will be a test after all. cc @karthikbtf
> > > > 
> > > > 
> > > > @charlie-tf all good! Lol Quick question, will 'patch' be applied to all PRs automatically? Will we be able to merge PRs that don't need a version bump?
> > > 
> > > 
> > > If you don't want a version bump, then you'd need to make sure there's no patch, minor, or major label on the PR prior to merging it. I pushed a commit (merge main) after removing the label, which kicked off another "Add Labels" job and re-added it. It's totally possible to merge without a version bump though.
> > 
> > 
> > Awesome, thanks!!
> 
> @karthikbtf Looks like it actually worked though! 🎉 image image

Woot!!! 🎉  I just saw the email after the check-in.
Thanks @charlie-tf - this is going to be so much easier to use. And no code-change to bump the version 🙌 
cc @constanzauanini

**Pull request merged**
