### PR TITLE
SW-2251: Update NavBar for nested hierarchy navigation (follow up)

### PR DESCRIPTION
**Pull request by joshbuchea**
This PR updates NavBar components based on feedback from @hannah-cai in [this PR comment](https://github.com/terraware/terraware-web/pull/768#issuecomment-1316032457).

### AFTER

Screen Shot 2022-11-15 at 3 34 19 PM

### BEFORE

Screen Shot 2022-11-15 at 3 37 04 PM

### CODE REVIEW

**Review by charlie-tf — APPROVED** [review]

**Comment by hannah-cai** [comment]
looks good! some notes:

> nav items should have 12px top and bottom padding, not 16.
left and right padding should still be at 16! once that's fixed the alignment between main and sub-navigation items should be fixed.

> nav item text should be font-weight medium (500). this is in the css but it doesn't render as medium for some reason. if you change it to 400 using dev tools it looks the same 🤔
this still seems to be an issue

> currently, the caret disappears when dropdowns are open. I think that we should still show them, like [this](https://www.figma.com/file/DftqOeGx8irCdRf7IZ4lbc/Navigation?node-id=4914%3A171226&viewport=300%2C280%2C0.31&t=07zs8VjirH46ZaWI-11). I think we should also keep the hover state, even though if you click it it won't do anything
the hover state wasn't added, but on second thought I prefer it this way. could we make dropdowns that are open not clickable at all? it's confusing right now to click on them expecting them to collapse, and instead be directed to the first tab under them.

**Comment by joshbuchea** [comment]
@hannah-cai

Sorry I missed the padding, I made the update locally but must have forgot to commit the changes. Will fix. The text in the sub nav items should align with text in the parent nav items, correct?

I'm not sure what to do about the font weight not rendering correctly if the font weight is correct in the CSS.  The only thing I can think of is our font file may be missing some font weights, but typically 500 is a font weight that's included in font files that only include a subset of font weights 🤔 @karthikbtf or @constanzauanini, do you know if our font file for the Inter font could be missing some font weights?

I tried adding the hover state but because of the component markup is currently the hover state applied to the parent & children — and it looked awkward. We can restructure the component, but it's more than a small lift and wasn't sure if we wanted to invest that much time for this. I can definitely update the parent nav items to either collapse or not be clickable at all.

**Comment by karthikbtf** [comment]
> @hannah-cai
> 
> Sorry I missed the padding, I made the update locally but must have forgot to commit the changes. Will fix. The text in the sub nav items should align with text in the parent nav items, correct?
> 
> I'm not sure what to do about the font weight not rendering correctly if the font weight is correct in the CSS. The only thing I can think of is our font file may be missing some font weights, but typically 500 is a font weight that's included in font files that only include a subset of font weights 🤔 @karthikbtf or @constanzauanini, do you know if our font file for the Inter font could be missing some font weights?
> 
> I tried adding the hover state but because of the component markup is currently the hover state applied to the parent & children — and it looked awkward. We can restructure the component, but it's more than a small lift and wasn't sure if we wanted to invest that much time for this. I can definitely update the parent nav items to not be clickable at all.

@joshbuchea we do have these font weights in terraware-web.
We should probably initialize web-components story book with the correct fonts. I can take a look at that.
Honestly, I don't know what the right procedure here is - should fonts come from web-components or should terraware-web handle it's own font sources. @constanzauanini ?

**Comment by karthikbtf** [comment]
> > @hannah-cai
> > Sorry I missed the padding, I made the update locally but must have forgot to commit the changes. Will fix. The text in the sub nav items should align with text in the parent nav items, correct?
> > I'm not sure what to do about the font weight not rendering correctly if the font weight is correct in the CSS. The only thing I can think of is our font file may be missing some font weights, but typically 500 is a font weight that's included in font files that only include a subset of font weights 🤔 @karthikbtf or @constanzauanini, do you know if our font file for the Inter font could be missing some font weights?
> > I tried adding the hover state but because of the component markup is currently the hover state applied to the parent & children — and it looked awkward. We can restructure the component, but it's more than a small lift and wasn't sure if we wanted to invest that much time for this. I can definitely update the parent nav items to not be clickable at all.
> 
> @joshbuchea we do have these font weights in terraware-web. We should probably initialize web-components story book with the correct fonts. I can take a look at that. Honestly, I don't know what the right procedure here is - should fonts come from web-components or should terraware-web handle it's own font sources. @constanzauanini ?

I have a PR out for the font weights https://github.com/terraware/web-components/pull/145

**Comment by constanzauanini** [comment]
> @hannah-cai
> 
> Sorry I missed the padding, I made the update locally but must have forgot to commit the changes. Will fix. The text in the sub nav items should align with text in the parent nav items, correct?
> 
> I'm not sure what to do about the font weight not rendering correctly if the font weight is correct in the CSS. The only thing I can think of is our font file may be missing some font weights, but typically 500 is a font weight that's included in font files that only include a subset of font weights 🤔 @karthikbtf or @constanzauanini, do you know if our font file for the Inter font could be missing some font weights?
> 
> I tried adding the hover state but because of the component markup is currently the hover state applied to the parent & children — and it looked awkward. We can restructure the component, but it's more than a small lift and wasn't sure if we wanted to invest that much time for this. I can definitely update the parent nav items to not be clickable at all.

In the readme of the font it says: This download contains Inter as both a variable font and static fonts.

Inter is a variable font with these axes:
  slnt
  wght

This means all the styles are contained in a single file:
  Inter-VariableFont_slnt,wght.ttf

If your app fully supports variable fonts, you can now pick intermediate styles
that aren’t available as static fonts. Not all apps support variable fonts, and
in those cases you can use the static font files for Inter:
  static/Inter-Thin.ttf
  static/Inter-ExtraLight.ttf
  static/Inter-Light.ttf
  static/Inter-Regular.ttf
  static/Inter-Medium.ttf
  static/Inter-SemiBold.ttf
  static/Inter-Bold.ttf
  static/Inter-ExtraBold.ttf
  static/Inter-Black.ttf

Maybe we need to add all the other fonts because our app doesn't support variable fonts? 
I think it's ok if the font comes from web-components, because we want the components to have that font.

**Comment by hannah-cai** [comment]
@joshbuchea 

> Sorry I missed the padding, I made the update locally but must have forgot to commit the changes. Will fix. The text in the sub nav items should align with text in the parent nav items, correct?

yup!

> I tried adding the hover state but because of the component markup is currently the hover state applied to the parent & children — and it looked awkward. We can restructure the component, but it's more than a small lift and wasn't sure if we wanted to invest that much time for this. I can definitely update the parent nav items to not be clickable at all.

hmm ok, let's just make them not clickable then, and not worry about the hover. thank you!

**Pull request merged**
