### PR TITLE
Updating all material and emotion packages to their latest compatible versions

### PR DESCRIPTION
**Pull request by nickgraz**

### CODE REVIEW

**Comment by nickgraz** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #453** <a href="https://app.graphite.dev/github/pr/terraware/web-components/453?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/terraware/web-components/453?utm_source=stack-comment).

**Comment by nickgraz** [comment]
publish rc

**Comment by nickgraz** [comment]
publish rc

**Comment by nickgraz** [comment]
publish rc

**Review by karthikbtf — APPROVED** [review]
Thanks for doing this. We have always had trouble bumping these packages, same theme not found errors. Constanza had some workaround which I can't recall.

**Comment by nickgraz** [comment]
I'm hopeful it ends up working in `terraware-web`, building the rc now

**Comment by nickgraz** [comment]
Graphite had some trouble with this one...

**Pull request merged**
