### PR TITLE
Fix the issue with Chrome > 126 blurring when focusing on child elements

### PR DESCRIPTION
**Pull request by nickgraz**

### CODE REVIEW

**Comment by nickgraz** [comment]
* **#631** <a href="https://app.graphite.dev/github/pr/terraware/web-components/631?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nickgraz and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by joshbuchea — APPROVED** [review]
Very nice! 💯

**Comment by nickgraz** [comment]
### Merge activity

* **Aug 21, 7:16 PM EDT**: @nickgraz started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/terraware/web-components/631).

**Comment by joshbuchea** [comment]
I'm very familiar with `event.currentTarget`, but I don't think I was aware of `event.relatedTarget` before today. Nice fix!

**Pull request merged**
