### PR TITLE
Refactor Dropdown components 

### PR DESCRIPTION
**Pull request by karthikbtf**
- use single component
- use 'autocomplete' boolean option to switch behavior

### CODE REVIEW

**Review by constanzauanini — APPROVED** [review]
Looks good to me! just don't understand why the other way (with the component and no the prop) didn't work

**Comment by karthikbtf** [comment]
> Looks good to me! just don't understand why the other way (with the component and no the prop) didn't work

This refactor is mostly to avoid having 2 components. And rename values to options in Autocomplete (to be consistent with options in Select.. and mui calls it options as well).

I'm still running into issues but could be my environment.
When I copy this code to terraware-web it works.. when I copy the web-components dist to my local env it doesn't.

**Comment by constanzauanini** [comment]
> > Looks good to me! just don't understand why the other way (with the component and no the prop) didn't work
> 
> This refactor is mostly to avoid having 2 components. And rename values to options in Autocomplete (to be consistent with options in Select.. and mui calls it options as well).
> 
> I'm still running into issues but could be my environment. When I copy this code to terraware-web it works.. when I copy the web-components dist to my local env it doesn't.

How do you copy this code to terraware-web?

**Comment by karthikbtf** [comment]
> > > Looks good to me! just don't understand why the other way (with the component and no the prop) didn't work
> > 
> > 
> > This refactor is mostly to avoid having 2 components. And rename values to options in Autocomplete (to be consistent with options in Select.. and mui calls it options as well).
> > I'm still running into issues but could be my environment. When I copy this code to terraware-web it works.. when I copy the web-components dist to my local env it doesn't.
> 
> How do you copy this code to terraware-web?

copy over dropdown component file and import from there (with some changes to import paths)..

**Comment by karthikbtf** [comment]
> > > > Looks good to me! just don't understand why the other way (with the component and no the prop) didn't work
> > > 
> > > 
> > > This refactor is mostly to avoid having 2 components. And rename values to options in Autocomplete (to be consistent with options in Select.. and mui calls it options as well).
> > > I'm still running into issues but could be my environment. When I copy this code to terraware-web it works.. when I copy the web-components dist to my local env it doesn't.
> > 
> > 
> > How do you copy this code to terraware-web?
> 
> copy over dropdown component file and import from there (with some changes to import paths)..

Error was in client code.

**Pull request merged**
