### PR TITLE
SW-5443 | SW-5442 | SW-5444 Update table styles

### PR DESCRIPTION
**Pull request by alexTerraformation**
Add striped row background. Increase cell font-size to 16px. Add hover and selected row styles.

### CODE REVIEW

**Comment by alexTerraformation** [comment]
publish-rc

**Review by nickgraz — APPROVED** [review]
Looks good to me!

**Comment by alexTerraformation** [comment]
publish rc

**Comment by alexTerraformation** [comment]
publish rc

**Pull request closed without merging**
