### PR TITLE
SW-2153 Message Update

### PR DESCRIPTION
**Pull request by charlie-tf**
- change corner radius
- change toast bg color
- ~change toast positioning~ (this is done in terraware-web)

Page Message, border-radius: 16px:
image

Toast Message:
image

### CODE REVIEW

**Comment by constanzauanini** [comment]
I'm seeing in Vercel that the "undo" in toast messages is always green (for info, critical, warning also). Is that correct?

**Comment by charlie-tf** [comment]
> I'm seeing in Vercel that the "undo" in toast messages is always green (for info, critical, warning also). Is that correct?

Semantically, it is a link, whose color is `$tw-clr-txt-brand` throughout the app now. @hannah-cai does it make sense to keep it this way for all toast message actions?

**Comment by hannah-cai** [comment]
> > I'm seeing in Vercel that the "undo" in toast messages is always green (for info, critical, warning also). Is that correct?
> 
> Semantically, it is a link, whose color is `$tw-clr-txt-brand` throughout the app now. @hannah-cai does it make sense to keep it this way for all toast message actions?

sorry this was unclear in the spec! to clarify, the toast messages should be using the same semantic tokens as the page messages. I've laid out all the colors [here](https://www.figma.com/file/aLIG1C6uIMyBWiTopSluxe/Visual-Refresh?node-id=2268%3A286871&viewport=-1545%2C-7993%2C0.58&t=iPCaOpWtSj4e3hRN-11). 
image

the green in the spec was actually outdated, we decided to use light green for our semantic success instead of the brand color. my bad for forgetting to update it!

**Comment by charlie-tf** [comment]
Thank you, @hannah-cai!! One outstanding question: should the action link (Undo in storybook) be the brand color?
image

**Comment by hannah-cai** [comment]
> Thank you, @hannah-cai!! One outstanding question: should the action link (Undo in storybook) be the brand color? image

yes, that's correct!

**Comment by hannah-cai** [comment]
> > > I'm seeing in Vercel that the "undo" in toast messages is always green (for info, critical, warning also). Is that correct?
> > 
> > 
> > Semantically, it is a link, whose color is `$tw-clr-txt-brand` throughout the app now. @hannah-cai does it make sense to keep it this way for all toast message actions?
> 
> sorry this was unclear in the spec! to clarify, the toast messages should be using the same semantic tokens as the page messages. I've laid out all the colors [here](https://www.figma.com/file/aLIG1C6uIMyBWiTopSluxe/Visual-Refresh?node-id=2281%3A287640&viewport=-3675%2C-15043%2C1.09&t=iPCaOpWtSj4e3hRN-11). image
> 
> the green in the spec was actually outdated, we decided to use light green for our semantic success instead of the brand color. my bad for forgetting to update it!

not sure if this was missed or if you just haven't gotten to it yet, but the green in the preview still looks like it's the brand green and not the light green

**Comment by charlie-tf** [comment]
>not sure if this was missed or if you just haven't gotten to it yet, but the green in the preview still looks like it's the brand green and not the light green

@hannah-cai oooh I see what you're saying. What is needed is for you or @chudo76 to change the definition of the semantic `success` colors within zeroheight and then create a PR into web-components with those changes, I believe

**Comment by chudo76** [comment]
> > not sure if this was missed or if you just haven't gotten to it yet, but the green in the preview still looks like it's the brand green and not the light green
> 
> @hannah-cai oooh I see what you're saying. What is needed is for you or @chudo76 to change the definition of the semantic `success` colors within zeroheight and then create a PR into web-components with those changes, I believe

@charlie-tf I updated the token file in zeroheight to reference the correct (light) green. The URL doesn't change and also, I wasn't sure which branch I'm supposed to run the "design changes workflow" in... Here's the token file link (no change to URL): https://terraformation.zeroheight.com/api/token_file/27c7140ddd23/share

**Comment by charlie-tf** [comment]
> > > not sure if this was missed or if you just haven't gotten to it yet, but the green in the preview still looks like it's the brand green and not the light green
> > 
> > 
> > @hannah-cai oooh I see what you're saying. What is needed is for you or @chudo76 to change the definition of the semantic `success` colors within zeroheight and then create a PR into web-components with those changes, I believe
> 
> @charlie-tf I updated the token file in zeroheight to reference the correct (light) green. The URL doesn't change and also, I wasn't sure which branch I'm supposed to run the "design changes workflow" in... Here's the token file link (no change to URL): https://terraformation.zeroheight.com/api/token_file/27c7140ddd23/share

Thanks so much @chudo76! I can go ahead and pull those changes into this PR. That's probably the most straightforward approach 👍

**Review by karthikbtf — APPROVED** [review]
👍

**Pull request merged**
