### PR TITLE
SW-5031 Set empty value on hidden file upload input

### PR DESCRIPTION
**Pull request by nickgraz**

### CODE REVIEW

**Comment by nickgraz** [comment]
* **#482** <a href="https://app.graphite.dev/github/pr/terraware/web-components/482?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nickgraz and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by nickgraz** [comment]
publish rc

**Review by karthikbtf — APPROVED** [review]
Woot! 🎉

**Comment by nickgraz** [comment]
And to think we almost wrote a bunch of code to fix, nice work my friend

**Pull request merged**
