### PR TITLE
SW-5445 Added density prop to table component, and settings icon

### PR DESCRIPTION
**Pull request by tommylau523**

### CODE REVIEW

**Comment by tommylau523** [comment]
* **#585** <a href="https://app.graphite.dev/github/pr/terraware/web-components/585?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @tommylau523 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by tommylau523** [comment]
publish rc

**Comment by tommylau523** [comment]
publish rc

**Comment by tommylau523** [comment]
publish rc

**Comment by tommylau523** [comment]
publish rc

**Review by joshbuchea — APPROVED** [review]
Changes look great, nice work!

**Comment by nickgraz** [comment]
Nice!

**Review by nickgraz — APPROVED** [review]

**Pull request merged**
