### PR TITLE
Update the style dictionary from ZeroHeight

### PR DESCRIPTION
**Pull request by nickgraz**

### CODE REVIEW

**Comment by nickgraz** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/terraware/web-components/454?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #453** <a href="https://app.graphite.dev/github/pr/terraware/web-components/453?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #454** <a href="https://app.graphite.dev/github/pr/terraware/web-components/454?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/terraware/web-components/454?utm_source=stack-comment).

**Review by karthikbtf — APPROVED** [review]
lgtm, looks backwards compatible (won't break terraware web or other apps?)

**Comment by nickgraz** [comment]
It seems like it is, there's a chance that the colors might change up a bit but there aren't any deletions so we should be good.

**Comment by nickgraz** [comment]
publish rc

**Comment by nickgraz** [comment]
publish rc

**Comment by nickgraz** [comment]
publish rc

**Pull request merged**
