### PR TITLE
SW-4503 Add the ability to inject a JSX element into the top bar buttons of the Table

### PR DESCRIPTION
**Pull request by nickgraz**

### CODE REVIEW

**Comment by nickgraz** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #449** <a href="https://app.graphite.dev/github/pr/terraware/web-components/449?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/terraware/web-components/449?utm_source=stack-comment).

**Comment by nickgraz** [comment]
publish rc

**Comment by nickgraz** [comment]
publish rc

**Comment by karthikbtf** [comment]
Triggered a new build, vercel deployment had failed.

**Review by karthikbtf — APPROVED** [review]

**Pull request merged**
