### PR TITLE
SW-2575 Allow toggling open state of nav hiearchy root

### PR DESCRIPTION
**Pull request by karthikbtf**
- we want to allow opening the hierarchy without selecting a menu item

Navbar - Default ⋅ Storybook 2022-12-20 17-02-15

### CODE REVIEW

**Comment by constanzauanini** [comment]
Why is seeds menu not closing on storybook?

**Comment by constanzauanini** [comment]
> Why is seeds menu not closing on storybook?

Oh, I see. It doesn't have to be selected to allow closing, is that the intended behavior?

**Comment by karthikbtf** [comment]
> Why is seeds menu not closing on storybook?

because it has a selected item - keeping current behavior in staging
we want to open other menus without auto selecting

**Review by constanzauanini — APPROVED** [review]

**Comment by karthikbtf** [comment]
> > Why is seeds menu not closing on storybook?
> 
> Oh, I see. It doesn't have to be selected to allow closing, is that the intended behavior?

behavior: allow opening a menu hierarchy without selecting a child menu. on mobile especially this is helpful
the requirements didn't say anything about existing menus that have a child menu selected so not changing that behavior - also if we close that user may be confused.
if they want changes we can iterate

**Pull request merged**
