### PR TITLE
SW-2631 Separate 'id' and 'propertyName' semantics in various web-components

### PR DESCRIPTION
**Pull request by karthikbtf**
- this allows us to use different ids for tracking purposes
- next step is to apply these changes in terraware-web

### CODE REVIEW

**Comment by constanzauanini** [comment]
Can you give an example in terraware-web where we need the id to be different from the propertyName ?

**Comment by karthikbtf** [comment]
> Can you give an example in terraware-web where we need the id to be different from the propertyName ?

Theoretically, everywhere. These are semantically different properties on an element.
One practical example: id='seed-bank-name' propertyName='name' (for editing a seed bank name)
We track by id in google analytics.

**Comment by karthikbtf** [comment]
> > Can you give an example in terraware-web where we need the id to be different from the propertyName ?
> 
> Theoretically, everywhere. These are semantically different properties on an element. One practical example: id='seed-bank-name' propertyName='name' (for editing a seed bank name) We track by id in google analytics.

Another way to do this is to remove 'id' being passed to the onChange callback. We can have the calling code handle it - that may be simpler. This may also be consistent with component frameworks (eg. mui)?
eg.
<component
  id='some-id'
  onChange=(value => setValue('name', value)}
/>

We can maybe discuss this in a team meeting.

**Comment by karthikbtf** [comment]
Updated the ticket with more details.

**Comment by constanzauanini** [comment]
> > > Can you give an example in terraware-web where we need the id to be different from the propertyName ?
> > 
> > 
> > Theoretically, everywhere. These are semantically different properties on an element. One practical example: id='seed-bank-name' propertyName='name' (for editing a seed bank name) We track by id in google analytics.
> 
> Another way to do this is to remove 'id' being passed to the onChange callback. We can have the calling code handle it - that may be simpler. This may also be consistent with component frameworks (eg. mui)? eg. <component id='some-id' onChange=(value => setValue('name', value)} />
> 
> We can maybe discuss this in a team meeting.

Yes, I think this option is simpler!

**Comment by karthikbtf** [comment]
> > > > Can you give an example in terraware-web where we need the id to be different from the propertyName ?
> > > 
> > > 
> > > Theoretically, everywhere. These are semantically different properties on an element. One practical example: id='seed-bank-name' propertyName='name' (for editing a seed bank name) We track by id in google analytics.
> > 
> > 
> > Another way to do this is to remove 'id' being passed to the onChange callback. We can have the calling code handle it - that may be simpler. This may also be consistent with component frameworks (eg. mui)? eg. <component id='some-id' onChange=(value => setValue('name', value)} />
> > We can maybe discuss this in a team meeting.
> 
> Yes, I think this option is simpler!

Thanks, Constanza. I closed this for now. We can discuss it in a meeting maybe, since it's a risky change but essential.

**Pull request closed without merging**
