### PR TITLE
SW-2712 Initialize theme the same way we do in terraware-web

### PR DESCRIPTION
**Pull request by constanzauanini**
Now the theme is initialized the same way as in terraware-web. 
Still need to update a dependency to check if this works

### CODE REVIEW

**Comment by karthikbtf** [comment]
Awesome thanks @constanzauanini - this will help catch issues before we publish new versions that fail in web.

**Comment by constanzauanini** [comment]
> Awesome thanks @constanzauanini - this will help catch issues before we publish new versions that fail in web.

Yes, I still want to test updating a dependency that breaks terraware-web, to see if it breaks here too

**Comment by constanzauanini** [comment]
I just tested updating "@mui/material" from "5.8.7" to "5.11.4" and it breaks here too (not only on terraware-web). So this is working

**Review by karthikbtf — APPROVED** [review]
awesome!! now we can try out the mui upgrades next time..
thanks @constanzauanini 🎉

**Comment by karthikbtf** [comment]
> I just tested updating "@mui/material" from "5.8.7" to "5.11.4" and it breaks here too (not only on terraware-web). So this is working

Thanks, sounds good!
btw i removed the patch label since we don't want a version bump for this change.

I think the next step is to figure out how to  upgrade mui successfully.. for later..

**Comment by constanzauanini** [comment]
> > I just tested updating "@mui/material" from "5.8.7" to "5.11.4" and it breaks here too (not only on terraware-web). So this is working
> 
> Thanks, sounds good! btw i removed the patch label since we don't want a version bump for this change.
> 
> I think the next step is to figure out how to upgrade mui successfully.. for later..

Yes, thanks for removing it!

**Pull request merged**
